---
# Elasticsearch
elasticsearch_host: "10.132.0.11"
elastic_password: "{{ vault_elastic_password }}"

# Kibana
kibana_host: "158.160.34.63"
kibana_password: "{{ vault_kibana_password }}"

# Zabbix
zabbix_password: "{{ vault_zabbix_password }}"

# Ansible settings
ansible_user: ubuntu
ansible_ssh_private_key_file: "~/.ssh/id_rsa_diploma"
