---
ansible_user: ubuntu
ansible_ssh_private_key_file: "~/.ssh/id_rsa_diploma"

# Zabbix settings
zabbix_server_ip: "zabbix.ru-central1.internal"
zabbix_server_host: "zabbix.ru-central1.internal"

# Elasticsearch settings  
elasticsearch_ip: "zabbix.ru-central1.internal"
elasticsearch_host: "zabbix.ru-central1.internal"

# Kibana settings
kibana_host: "zabbix.ru-central1.internal"
