---
- name: Create elasticsearch directory
  file:
    path: /home/ubuntu/elasticsearch
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Copy docker-compose for elasticsearch
  template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/elasticsearch/docker-compose.yml
    owner: ubuntu
    group: ubuntu

- name: Start elasticsearch
  community.docker.docker_compose:
    project_src: /home/ubuntu/elasticsearch
    state: present

- name: Wait for elasticsearch to start
  wait_for:
    port: 9200
    host: "{{ ansible_default_ipv4.address }}"
    delay: 30
    timeout: 120
