all:
  children:
    bastion:
      hosts:
        bastion:
          ansible_host: 89.169.145.11

    webservers:
      hosts:
        web1:
          ansible_host: 10.132.0.32
        web2:
          ansible_host: 10.133.0.3

    zabbix:
      hosts:
        zabbix:
          ansible_host: 158.160.107.7

    elasticsearch:
      hosts:
        elastic:
          ansible_host: 10.132.0.11

    kibana:
      hosts:
        kibana:
          ansible_host: 158.160.34.63

  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@89.169.145.11"'
